stages:
  - install
  - build
  - test

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install-dependencies:
  stage: install
  script:
    - pnpm install

build-project:
  stage: build
  script:
    - pnpm build

typechecking:
  stage: test
  script:
    - tsc

eslint:
  stage: test
  script:
    - pnpm lint

unit:
  stage: test
  script:
    - pnpm test:no-watch