stages:
  - install
  - build

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install-dependencies:
  stage: install
  script:
    - pnpm install

build-project:
  stage: build
  script:
    - pnpm build