build-job:
  stage: build
  script:
    - pwd
    - which npm
    - npm -v
    - pnpm -v
    - pnpm build

tsc-job:
  stage: test
  script:
    - tsc

eslint-job:
  stage: test
  script:
    - pnpm lint